# Generated by Django 4.2.7 on 2025-11-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_name", models.CharField(default="شهر راز", max_length=100)),
                (
                    "site_title",
                    models.CharField(
                        default="راه\u200cحل جامع برای تمام نیازهای مالی و حقوقی شما",
                        max_length=200,
                    ),
                ),
                (
                    "site_description",
                    models.TextField(
                        default="شهر راز با بیش از ۱۵ سال تجربه، ارائه\u200cدهنده خدمات تخصصی خرید و فروش وام، لیزینگ خودرو، ثبت شرکت، خدمات حقوقی و قضایی، ثبت مجوزها و کارت\u200cهای بازرگانی است."
                    ),
                ),
                (
                    "hero_badge",
                    models.CharField(
                        default="✨ مرکز تخصصی خدمات مالی و حقوقی", max_length=100
                    ),
                ),
                (
                    "hero_subtitle",
                    models.TextField(
                        default="شهر راز با بیش از ۱۵ سال تجربه، ارائه\u200cدهنده خدمات تخصصی خرید و فروش وام، لیزینگ خودرو، ثبت شرکت، خدمات حقوقی و قضایی، ثبت مجوزها و کارت\u200cهای بازرگانی است. ما با تیم متخصص و سیستم\u200cهای پیشرفته، بهترین راه\u200cحل را برای شما فراهم می\u200cکنیم."
                    ),
                ),
                (
                    "services_title",
                    models.CharField(default="خدمات تخصصی ما", max_length=100),
                ),
                (
                    "services_subtitle",
                    models.CharField(
                        default="مجموعه کامل خدمات مالی و حقوقی در یک مکان",
                        max_length=200,
                    ),
                ),
                (
                    "service_loan_title",
                    models.CharField(default="خرید و فروش وام", max_length=100),
                ),
                (
                    "service_loan_description",
                    models.TextField(
                        default="خرید و فروش انواع وام\u200cهای بانکی با بهترین نرخ و شرایط. ما واسطه معتبر بین خریداران و فروشندگان وام هستیم."
                    ),
                ),
                (
                    "service_leasing_title",
                    models.CharField(default="لیزینگ خودرو", max_length=100),
                ),
                (
                    "service_leasing_description",
                    models.TextField(
                        default="ارائه خدمات لیزینگ خودرو با شرایط ویژه و اقساط مناسب. خرید خودرو بدون دغدغه مالی با لیزینگ شهر راز."
                    ),
                ),
                (
                    "service_registration_title",
                    models.CharField(default="ثبت شرکت", max_length=100),
                ),
                (
                    "service_registration_description",
                    models.TextField(
                        default="ثبت انواع شرکت\u200cها شامل سهامی خاص، با مسئولیت محدود، تعاونی و... با سرعت و دقت بالا."
                    ),
                ),
                (
                    "service_legal_title",
                    models.CharField(default="خدمات حقوقی و قضایی", max_length=100),
                ),
                (
                    "service_legal_description",
                    models.TextField(
                        default="ارائه مشاوره حقوقی، وکالت در دادگاه\u200cها، تنظیم قراردادها و پیگیری امور قضایی توسط وکلای مجرب."
                    ),
                ),
                (
                    "service_licenses_title",
                    models.CharField(default="ثبت مجوزها", max_length=100),
                ),
                (
                    "service_licenses_description",
                    models.TextField(
                        default="اخذ و ثبت انواع مجوزهای کسب\u200cوکار، پروانه\u200cهای صنفی، مجوزهای بهداشتی و صنعتی."
                    ),
                ),
                (
                    "service_commercial_title",
                    models.CharField(default="کارت بازرگانی", max_length=100),
                ),
                (
                    "service_commercial_description",
                    models.TextField(
                        default="اخذ و تمدید کارت بازرگانی، ثبت کدهای اقتصادی و انجام امور مربوط به واردات و صادرات."
                    ),
                ),
                (
                    "features_title",
                    models.CharField(default="چرا شهر راز؟", max_length=100),
                ),
                (
                    "features_subtitle",
                    models.CharField(
                        default="دلایلی که ما را متمایز می\u200cکند", max_length=200
                    ),
                ),
                (
                    "footer_company_name",
                    models.CharField(default="شهر راز", max_length=100),
                ),
                (
                    "footer_company_description",
                    models.TextField(
                        default="شرکت خدمات حقوقی تخصصی با بیش از ۱۵ سال تجربه در ارائه بهترین خدمات حقوقی"
                    ),
                ),
                (
                    "footer_address_title",
                    models.CharField(default="آدرس دفتر", max_length=100),
                ),
                (
                    "footer_address",
                    models.TextField(
                        default="تهران، خیابان آزادی، پلاک ۱۲۳\nطبقه ۵، واحد ۱۰"
                    ),
                ),
                (
                    "footer_hours_title",
                    models.CharField(default="ساعات کاری", max_length=100),
                ),
                (
                    "footer_hours",
                    models.TextField(
                        default="شنبه تا چهارشنبه: ۹ صبح تا ۶ عصر\nپنجشنبه: ۹ صبح تا ۱ ظهر"
                    ),
                ),
                (
                    "contact_phone_title",
                    models.CharField(default="تماس با ما", max_length=100),
                ),
                (
                    "contact_phone",
                    models.CharField(default="۰۲۱-۱۲۳۴۵۶۷۸", max_length=100),
                ),
                (
                    "trust_title",
                    models.CharField(default="چرا به ما اعتماد کنید؟", max_length=100),
                ),
                (
                    "trust_subtitle",
                    models.CharField(
                        default="آمار و ارقام گویای کیفیت خدمات ما", max_length=200
                    ),
                ),
                (
                    "faq_title",
                    models.CharField(default="سوالات متداول", max_length=100),
                ),
                (
                    "faq_subtitle",
                    models.CharField(default="پاسخ به سوالات رایج شما", max_length=200),
                ),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
    ]
