# Generated by Django 5.2.7 on 2025-11-19 13:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="دسته\u200cبندی", max_length=100, verbose_name="نام"
                    ),
                ),
                (
                    "icon",
                    models.CharField(default="📂", max_length=50, verbose_name="آیکون"),
                ),
                (
                    "description",
                    models.TextField(
                        default="توضیحات دسته\u200cبندی", verbose_name="توضیحات"
                    ),
                ),
            ],
            options={
                "verbose_name": "دسته\u200cبندی",
                "verbose_name_plural": "دسته\u200cبندی\u200cها",
            },
        ),
        migrations.CreateModel(
            name="Comparison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criterion",
                    models.CharField(
                        default="معیار", max_length=100, verbose_name="معیار"
                    ),
                ),
                (
                    "our_value",
                    models.CharField(
                        default="مقدار ما", max_length=100, verbose_name="مقدار ما"
                    ),
                ),
                (
                    "others_value",
                    models.CharField(
                        default="مقدار دیگران",
                        max_length=100,
                        verbose_name="مقدار دیگران",
                    ),
                ),
            ],
            options={
                "verbose_name": "مقایسه",
                "verbose_name_plural": "مقایسه\u200cها",
            },
        ),
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        default="021-1234-5678", max_length=20, verbose_name="تلفن"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        default="info@shahreraze.com",
                        max_length=254,
                        verbose_name="ایمیل",
                    ),
                ),
                (
                    "address",
                    models.TextField(default="تهران، ایران", verbose_name="آدرس"),
                ),
                (
                    "map_embed",
                    models.TextField(blank=True, default="", verbose_name="کد نقشه"),
                ),
            ],
            options={
                "verbose_name": "اطلاعات تماس",
                "verbose_name_plural": "اطلاعات تماس",
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question",
                    models.CharField(
                        default="سؤال", max_length=200, verbose_name="سؤال"
                    ),
                ),
                ("answer", models.TextField(default="پاسخ", verbose_name="پاسخ")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ترتیب")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
            ],
            options={
                "verbose_name": "سؤال متداول",
                "verbose_name_plural": "سؤالات متداول",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="HeroSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "headline",
                    models.CharField(
                        default="خدمات مالی و حقوقی جامع",
                        max_length=200,
                        verbose_name="عنوان",
                    ),
                ),
                (
                    "subheadline",
                    models.TextField(
                        default="خدمات حرفه\u200cای برای تمام نیازهای مالی و حقوقی شما",
                        verbose_name="زیرعنوان",
                    ),
                ),
                (
                    "cta_primary_text",
                    models.CharField(
                        default="تماس با ما",
                        max_length=100,
                        verbose_name="متن دکمه اصلی",
                    ),
                ),
                (
                    "cta_primary_link",
                    models.URLField(default="#contact", verbose_name="لینک دکمه اصلی"),
                ),
                (
                    "cta_secondary_text",
                    models.CharField(
                        default="مشاهده خدمات",
                        max_length=100,
                        verbose_name="متن دکمه ثانویه",
                    ),
                ),
                (
                    "cta_secondary_link",
                    models.URLField(
                        default="#services", verbose_name="لینک دکمه ثانویه"
                    ),
                ),
                (
                    "background_image",
                    models.ImageField(
                        blank=True,
                        upload_to="hero/",
                        verbose_name="تصویر پس\u200cزمینه",
                    ),
                ),
            ],
            options={
                "verbose_name": "بخش هرو",
                "verbose_name_plural": "بخش هرو",
            },
        ),
        migrations.CreateModel(
            name="LeasingOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="لیزینگ خودرو", max_length=100, verbose_name="عنوان"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        default="توضیحات پیشنهاد لیزینگ", verbose_name="توضیحات"
                    ),
                ),
                (
                    "features",
                    models.TextField(
                        default="ویژگی 1\nویژگی 2\nویژگی 3",
                        help_text="هر ویژگی را در یک خط وارد کنید",
                        verbose_name="ویژگی\u200cها",
                    ),
                ),
                (
                    "stats",
                    models.TextField(
                        default="قیمت:10000\nمدت:24 ماه",
                        help_text="آمارها را به فرمت: برچسب:مقدار (در هر خط یکی) وارد کنید",
                        verbose_name="آمارها",
                    ),
                ),
            ],
            options={
                "verbose_name": "پیشنهاد لیزینگ",
                "verbose_name_plural": "پیشنهادات لیزینگ",
            },
        ),
        migrations.CreateModel(
            name="LoanCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="دسته\u200cبندی وام",
                        max_length=100,
                        verbose_name="عنوان",
                    ),
                ),
                (
                    "icon",
                    models.CharField(default="💰", max_length=50, verbose_name="آیکون"),
                ),
                (
                    "description",
                    models.TextField(
                        default="توضیحات دسته\u200cبندی وام", verbose_name="توضیحات"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ترتیب")),
            ],
            options={
                "verbose_name": "دسته\u200cبندی وام",
                "verbose_name_plural": "دسته\u200cبندی وام\u200cها",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="خدمات", max_length=100, verbose_name="عنوان"
                    ),
                ),
                (
                    "icon",
                    models.CharField(default="🔧", max_length=50, verbose_name="آیکون"),
                ),
                (
                    "short_description",
                    models.TextField(
                        default="توضیحات خدمات", verbose_name="توضیحات کوتاه"
                    ),
                ),
                (
                    "content",
                    models.TextField(default="محتوای کامل خدمات", verbose_name="محتوا"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ترتیب")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
            ],
            options={
                "verbose_name": "خدمات",
                "verbose_name_plural": "خدمات",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="شهر راز", max_length=100, verbose_name="نام سایت"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        default="خدمات مالی و حقوقی تخصصی", verbose_name="توضیحات"
                    ),
                ),
                (
                    "address",
                    models.TextField(default="تهران، ایران", verbose_name="آدرس"),
                ),
                (
                    "phone_main",
                    models.CharField(
                        default="021-1234-5678", max_length=20, verbose_name="تلفن اصلی"
                    ),
                ),
                (
                    "phone_alt",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        verbose_name="تلفن جایگزین",
                    ),
                ),
                (
                    "email_main",
                    models.EmailField(
                        default="info@shahreraze.com",
                        max_length=254,
                        verbose_name="ایمیل اصلی",
                    ),
                ),
                (
                    "email_support",
                    models.EmailField(
                        default="support@shahreraze.com",
                        max_length=254,
                        verbose_name="ایمیل پشتیبانی",
                    ),
                ),
                (
                    "work_hours",
                    models.CharField(
                        default="شنبه-پنجشنبه: 9صبح-6عصر",
                        max_length=100,
                        verbose_name="ساعات کاری",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, upload_to="logos/", verbose_name="لوگو"
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True, upload_to="favicons/", verbose_name="آیکون"
                    ),
                ),
                (
                    "meta_keywords",
                    models.TextField(
                        blank=True, default="", verbose_name="کلمات کلیدی متا"
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True, default="", verbose_name="توضیحات متا"
                    ),
                ),
                (
                    "footer_text",
                    models.TextField(
                        default="© 2025 شهر راز. تمامی حقوق محفوظ است.",
                        verbose_name="متن فوتر",
                    ),
                ),
                (
                    "head_office_address",
                    models.TextField(
                        default="تهران، خیابان آزادی، پلاک ۱۲۳",
                        verbose_name="آدرس دفتر مرکزی",
                    ),
                ),
                (
                    "branch_office_address",
                    models.TextField(blank=True, default="", verbose_name="آدرس شعبه"),
                ),
            ],
            options={
                "verbose_name": "تنظیمات سایت",
                "verbose_name_plural": "تنظیمات سایت",
            },
        ),
        migrations.CreateModel(
            name="Statistic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="مشتریان", max_length=100, verbose_name="عنوان"
                    ),
                ),
                ("value", models.IntegerField(default=100, verbose_name="مقدار")),
                (
                    "icon",
                    models.CharField(default="👥", max_length=50, verbose_name="آیکون"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ترتیب")),
            ],
            options={
                "verbose_name": "آمار",
                "verbose_name_plural": "آمارها",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_name",
                    models.CharField(
                        default="مشتری", max_length=100, verbose_name="نام مشتری"
                    ),
                ),
                (
                    "client_role",
                    models.CharField(
                        default="نقش مشتری", max_length=100, verbose_name="نقش مشتری"
                    ),
                ),
                ("comment", models.TextField(default="نظر مشتری", verbose_name="نظر")),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        default=5,
                        verbose_name="امتیاز",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, upload_to="testimonials/", verbose_name="تصویر"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در حال بررسی"),
                            ("approved", "تایید شده"),
                            ("rejected", "رد شده"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاریخ ایجاد"
                    ),
                ),
            ],
            options={
                "verbose_name": "نظر مشتری",
                "verbose_name_plural": "نظرات مشتریان",
            },
        ),
        migrations.CreateModel(
            name="WhyUsFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="ویژگی", max_length=100, verbose_name="عنوان"
                    ),
                ),
                (
                    "icon",
                    models.CharField(default="⭐", max_length=50, verbose_name="آیکون"),
                ),
                (
                    "description",
                    models.TextField(default="توضیحات ویژگی", verbose_name="توضیحات"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ترتیب")),
            ],
            options={
                "verbose_name": "ویژگی ما",
                "verbose_name_plural": "ویژگی\u200cهای ما",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="LoanItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="آیتم وام", max_length=100, verbose_name="عنوان"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        default="توضیحات آیتم وام", verbose_name="توضیحات"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.loancategory",
                        verbose_name="دسته\u200cبندی",
                    ),
                ),
            ],
            options={
                "verbose_name": "آیتم وام",
                "verbose_name_plural": "آیتم\u200cهای وام",
            },
        ),
        migrations.CreateModel(
            name="ServiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="آیتم خدمات", max_length=100, verbose_name="عنوان"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        default="توضیحات آیتم خدمات", verbose_name="توضیحات"
                    ),
                ),
                (
                    "cta_text",
                    models.CharField(
                        default="اطلاعات بیشتر",
                        max_length=100,
                        verbose_name="متن دکمه عملیات",
                    ),
                ),
                (
                    "cta_link",
                    models.URLField(default="#", verbose_name="لینک دکمه عملیات"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.category",
                        verbose_name="دسته\u200cبندی",
                    ),
                ),
            ],
            options={
                "verbose_name": "آیتم خدمات",
                "verbose_name_plural": "آیتم\u200cهای خدمات",
            },
        ),
    ]
