# Generated by Django 5.2.7 on 2025-11-19 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollaborationProcess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="فرآیند همکاری با ما",
                        max_length=150,
                        verbose_name="عنوان بخش",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        default="مراحل ساده برای شروع همکاری با تیم شهر راز.",
                        help_text="توضیح کلی بخش، در بالای مراحل نمایش داده می\u200cشود.",
                        verbose_name="توضیحات",
                    ),
                ),
                (
                    "cta_text",
                    models.CharField(
                        default="شروع همکاری", max_length=100, verbose_name="متن دکمه"
                    ),
                ),
                (
                    "cta_link",
                    models.URLField(default="#contact", verbose_name="لینک دکمه"),
                ),
            ],
            options={
                "verbose_name": "بخش فرآیند همکاری",
                "verbose_name_plural": "بخش فرآیند همکاری",
            },
        ),
        migrations.CreateModel(
            name="CollaborationStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="مرحله", max_length=100, verbose_name="عنوان مرحله"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        default="توضیح مختصر از این مرحله.",
                        verbose_name="توضیحات مرحله",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ترتیب")),
                (
                    "icon",
                    models.CharField(
                        blank=True, default="✅", max_length=50, verbose_name="آیکون"
                    ),
                ),
                (
                    "process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="website.collaborationprocess",
                        verbose_name="بخش فرآیند",
                    ),
                ),
            ],
            options={
                "verbose_name": "مرحله همکاری",
                "verbose_name_plural": "مراحل همکاری",
                "ordering": ["order"],
            },
        ),
    ]
