# Generated by Django 4.2.7 on 2025-11-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="comparison_subtitle",
            field=models.CharField(
                default="چرا شهر راز بهترین انتخاب است", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="comparison_title",
            field=models.CharField(default="مقایسه ما با دیگران", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="contact_subtitle",
            field=models.CharField(
                default="برای مشاوره رایگان با ما در تماس باشید", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="contact_title",
            field=models.CharField(default="تماس با ما", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="cta_description",
            field=models.TextField(
                default="همین حالا با ما تماس بگیرید و از مشاوره رایگان بهره\u200cمند شوید"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="cta_title",
            field=models.CharField(default="آماده شروع همکاری هستید؟", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="faq_1_answer",
            field=models.TextField(
                default="برای فروش وام، کافی است با ما تماس بگیرید و مشخصات وام خود را اعلام کنید. کارشناسان ما پس از بررسی، بهترین قیمت را به شما پیشنهاد می\u200cدهند و در صورت توافق، فرآیند انتقال وام آغاز می\u200cشود."
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="faq_1_question",
            field=models.CharField(
                default="چگونه می\u200cتوانم وام خود را بفروشم؟", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="faq_2_answer",
            field=models.TextField(
                default="خیر، یکی از مزایای لیزینگ خودرو در شهر راز این است که نیازی به ضامن ندارد. شما می\u200cتوانید با ارائه مدارک شناسایی و اثبات درآمد، از این خدمات استفاده کنید."
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="faq_2_question",
            field=models.CharField(
                default="آیا لیزینگ خودرو نیاز به ضامن دارد؟", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="faq_3_answer",
            field=models.TextField(
                default="مدت زمان ثبت شرکت بسته به نوع شرکت و کامل بودن مدارک، معمولاً بین 3 تا 7 روز کاری است. تیم ما تمام تلاش خود را می\u200cکند تا این فرآیند در کوتاه\u200cترین زمان ممکن انجام شود."
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="faq_3_question",
            field=models.CharField(
                default="مدت زمان ثبت شرکت چقدر است؟", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="faq_4_answer",
            field=models.TextField(
                default="بله، مشاوره اولیه در تمام بخش\u200cهای خدمات ما کاملاً رایگان است. شما می\u200cتوانید با تماس با ما، از مشاوران متخصص ما راهنمایی\u200cهای لازم را دریافت کنید."
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="faq_4_question",
            field=models.CharField(
                default="آیا مشاوره اولیه رایگان است؟", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="faq_5_answer",
            field=models.TextField(
                default="هزینه خدمات حقوقی بسته به نوع پرونده، پیچیدگی موضوع و زمان مورد نیاز متفاوت است. ما پس از بررسی اولیه پرونده، هزینه\u200cها را به صورت شفاف و دقیق به شما اعلام می\u200cکنیم."
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="faq_5_question",
            field=models.CharField(
                default="هزینه خدمات حقوقی چگونه محاسبه می\u200cشود؟", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="faq_6_answer",
            field=models.TextField(
                default="برای دریافت کارت بازرگانی، ابتدا باید شرکت خود را ثبت کنید. سپس با ارائه مدارک مورد نیاز به اتاق بازرگانی، می\u200cتوانید کارت بازرگانی دریافت کنید. تیم ما تمام این مراحل را برای شما انجام می\u200cدهد."
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="faq_6_question",
            field=models.CharField(
                default="چگونه می\u200cتوانم کارت بازرگانی دریافت کنم؟", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="feature_1_description",
            field=models.TextField(
                default="تیم با تجربه و کارشناسی در حل مسائل حقوقی متنوع و پیچیده"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="feature_1_title",
            field=models.CharField(default="تجربه بیش از ۱۵ سال", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="feature_2_description",
            field=models.TextField(
                default="خدمات با کیفیت بالا و مناسب\u200cترین قیمت برای تمام طبقات"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="feature_2_title",
            field=models.CharField(default="نرخ\u200cهای رقابتی", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="feature_3_description",
            field=models.TextField(
                default="پاسخگویی فوری به تمام درخواست\u200cها و سؤال\u200cهای کلاینت\u200cها"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="feature_3_title",
            field=models.CharField(default="پاسخ سریع", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="feature_4_description",
            field=models.TextField(
                default="محفوظ بودن کامل اطلاعات و فایل\u200cهای قضایی شما"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="feature_4_title",
            field=models.CharField(default="محرمانگی و امنیت", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="feature_5_description",
            field=models.TextField(
                default="دسترسی دائمی به تیم حقوقی ما در تمام ساعات"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="feature_5_title",
            field=models.CharField(default="پشتیبانی ۲۴/۷", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="feature_6_description",
            field=models.TextField(
                default="سیستمی پیشرفته برای مدیریت پرونده\u200cها و مستندات"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="feature_6_title",
            field=models.CharField(default="سیستم دیجیتال", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="feature_7_description",
            field=models.TextField(
                default="بررسی دقیق و تحلیل جامع هر پرونده قبل از شروع دفاع"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="feature_7_title",
            field=models.CharField(default="تجزیه و تحلیل عمیق", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="feature_8_description",
            field=models.TextField(
                default="تمرکز بر دستیابی به بهترین نتایج برای هر پرونده"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="feature_8_title",
            field=models.CharField(default="نتایج اثربخش", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_about_title",
            field=models.CharField(default="درباره ما", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_copyright",
            field=models.CharField(
                default="۱۴۰۲ شهر راز - تمام حقوق محفوظ است.", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_legal_title",
            field=models.CharField(default="حقوقی", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_services_title",
            field=models.CharField(default="خدمات", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="leasing_benefit_1",
            field=models.CharField(default="بدون پیش\u200cپرداخت", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="leasing_benefit_2",
            field=models.CharField(default="اقساط بلندمدت", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="leasing_benefit_3",
            field=models.CharField(default="بدون ضامن", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="leasing_benefit_4",
            field=models.CharField(default="بدون وثیقه", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="leasing_description",
            field=models.TextField(
                default="خرید خودرو دیگر دغدغه شما نیست! با لیزینگ شهر راز، خودروی مورد نظر خود را با اقساط بلندمدت و بدون نیاز به وثیقه سنگین تهیه کنید."
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="leasing_stat_1_label",
            field=models.CharField(default="پیش\u200cپرداخت", max_length=50),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="leasing_stat_1_value",
            field=models.CharField(default="0%", max_length=20),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="leasing_stat_2_label",
            field=models.CharField(default="ماه قسط", max_length=50),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="leasing_stat_2_value",
            field=models.CharField(default="60", max_length=20),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="leasing_stat_3_label",
            field=models.CharField(default="تاییدیه", max_length=50),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="leasing_stat_3_value",
            field=models.CharField(default="99%", max_length=20),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="leasing_title",
            field=models.CharField(
                default="لیزینگ خودرو با شرایط استثنایی", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="loan_business_description",
            field=models.CharField(
                default="تامین مالی برای کسب\u200cوکارها", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="loan_business_features",
            field=models.TextField(
                default="وام سرمایه در گردش\nوام خرید ماشین\u200cآلات\nتسهیلات تولیدی\nوام توسعه کسب\u200cوکار"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="loan_business_title",
            field=models.CharField(default="وام کسب\u200cوکار", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="loan_car_description",
            field=models.CharField(
                default="معامله وام خرید خودرو با نرخ رقابتی", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="loan_car_features",
            field=models.TextField(
                default="وام خرید خودرو\nوام نوسازی خودرو\nتسهیلات خودرویی\nلیزینگ خودرو"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="loan_car_title",
            field=models.CharField(default="وام خودرو", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="loan_investment_description",
            field=models.CharField(
                default="تسهیلات برای سرمایه\u200cگذاری", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="loan_investment_features",
            field=models.TextField(
                default="وام سرمایه\u200cگذاری\nتسهیلات پروژه\u200cای\nوام مشارکتی\nتامین مالی پروژه"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="loan_investment_title",
            field=models.CharField(default="وام سرمایه\u200cگذاری", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="loan_mortgage_description",
            field=models.CharField(
                default="خرید و فروش وام مسکن با شرایط ویژه", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="loan_mortgage_features",
            field=models.TextField(
                default="وام خرید مسکن\nوام ودیعه مسکن\nوام بازسازی\nوام تعمیرات"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="loan_mortgage_title",
            field=models.CharField(default="وام مسکن", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="loan_services_subtitle",
            field=models.CharField(
                default="خرید و فروش انواع وام با بهترین قیمت و شرایط", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="loan_services_title",
            field=models.CharField(
                default="انواع وام\u200cهای قابل معامله", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="process_step_1_description",
            field=models.TextField(
                default="با ما تماس بگیرید و نیاز خود را بیان کنید. مشاوران ما به صورت رایگان راهنمایی\u200cهای لازم را ارائه می\u200cدهند."
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="process_step_1_title",
            field=models.CharField(default="تماس و مشاوره", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="process_step_2_description",
            field=models.TextField(
                default="تیم متخصص ما درخواست شما را بررسی کرده و بهترین راه\u200cحل را با توجه به شرایط شما پیشنهاد می\u200cدهند."
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="process_step_2_title",
            field=models.CharField(default="بررسی و ارزیابی", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="process_step_3_description",
            field=models.TextField(
                default="پس از تایید، فرآیند اجرا آغاز می\u200cشود و تیم ما تمام مراحل را با دقت پیگیری می\u200cکنند."
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="process_step_3_title",
            field=models.CharField(default="اجرا و پیگیری", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="process_step_4_description",
            field=models.TextField(
                default="پس از اتمام کار، مدارک و خدمات به شما تحویل داده شده و پشتیبانی پس از فروش ارائه می\u200cشود."
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="process_step_4_title",
            field=models.CharField(default="تحویل و پشتیبانی", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="process_subtitle",
            field=models.CharField(
                default="چهار گام ساده تا رسیدن به هدف شما", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="process_title",
            field=models.CharField(default="فرآیند همکاری با ما", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="registration_commercial_features",
            field=models.TextField(
                default="اخذ کارت بازرگانی\nتمدید کارت بازرگانی\nثبت کد اقتصادی\nثبت کد IEC\nمجوز واردات و صادرات\nثبت برند و علامت تجاری"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="registration_commercial_title",
            field=models.CharField(default="کارت بازرگانی", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="registration_company_features",
            field=models.TextField(
                default="ثبت شرکت سهامی خاص\nثبت شرکت با مسئولیت محدود\nثبت شرکت تعاونی\nثبت شرکت تضامنی\nتغییرات شرکت\nانحلال و ادغام شرکت"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="registration_company_title",
            field=models.CharField(default="ثبت انواع شرکت", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="registration_license_features",
            field=models.TextField(
                default="مجوز کسب\u200cوکار\nپروانه صنفی\nمجوز بهداشتی\nمجوز صنعتی\nمجوز ساختمانی\nمجوزهای تخصصی"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="registration_license_title",
            field=models.CharField(default="اخذ مجوزها", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="registration_subtitle",
            field=models.CharField(
                default="ثبت شرکت، اخذ مجوزها و کارت بازرگانی با سرعت و دقت",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="registration_title",
            field=models.CharField(default="خدمات ثبتی و مجوزها", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="testimonial_1_author",
            field=models.CharField(default="علی محمدی", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="testimonial_1_position",
            field=models.CharField(default="مدیرعامل شرکت", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="testimonial_1_text",
            field=models.TextField(
                default="تیم شهر راز واقعاً حرفه\u200cای و باتجربه است. پرونده\u200cی ما را در کمترین وقت و بهترین نتیجه حل کردند. توصیه می\u200cکنم!"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="testimonial_2_author",
            field=models.CharField(default="فاطمه احمدی", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="testimonial_2_position",
            field=models.CharField(default="مالک کسب\u200cو\u200cکار", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="testimonial_2_text",
            field=models.TextField(
                default="خدمات بسیار حرفه\u200cای و کاملاً شفاف. هیچ هزینه پنهانی نداشت و نتیجه عالی بود. ممنونم!"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="testimonial_3_author",
            field=models.CharField(default="حسن رضایی", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="testimonial_3_position",
            field=models.CharField(default="بازرگان", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="testimonial_3_text",
            field=models.TextField(
                default="سرعت پاسخگویی و مشاوره عالی. پیشنهادات قیمت رقابتی و نتایج بهتر از انتظار. بسیار رضایت\u200cمند!"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="testimonials_subtitle",
            field=models.CharField(default="تجربه همکاری با ما", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="testimonials_title",
            field=models.CharField(default="نظرات مشتریان", max_length=100),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="trust_stat_1_label",
            field=models.CharField(default="مشتری راضی", max_length=50),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="trust_stat_1_value",
            field=models.CharField(default="2000+", max_length=20),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="trust_stat_2_label",
            field=models.CharField(default="رضایت مشتریان", max_length=50),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="trust_stat_2_value",
            field=models.CharField(default="98%", max_length=20),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="trust_stat_3_label",
            field=models.CharField(default="سال تجربه", max_length=50),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="trust_stat_3_value",
            field=models.CharField(default="15+", max_length=20),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="trust_stat_4_label",
            field=models.CharField(default="متخصص حرفه\u200cای", max_length=50),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="trust_stat_4_value",
            field=models.CharField(default="50+", max_length=20),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="trust_stat_5_label",
            field=models.CharField(default="پروژه موفق", max_length=50),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="trust_stat_5_value",
            field=models.CharField(default="5000+", max_length=20),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="trust_stat_6_label",
            field=models.CharField(default="پشتیبانی", max_length=50),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="trust_stat_6_value",
            field=models.CharField(default="24/7", max_length=20),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="contact_phone",
            field=models.CharField(
                default="021-1234-5678\n0912-345-6789", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="contact_phone_title",
            field=models.CharField(default="تلفن تماس", max_length=100),
        ),
    ]
