# Generated by Django 5.2.7 on 2025-11-01 21:52

from django.db import migrations, models
import django.utils.timezone
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_sitesettings_comparison_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='site_keywords',
            field=models.TextField(default='خرید وام, فروش وام, لیزینگ خودرو, ثبت شرکت, خدمات حقوقی, وکالت, ثبت مجوز', verbose_name='کلمات کلیدی'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_author',
            field=models.CharField(default='Shahrar Financial & Legal Services', max_length=100, verbose_name='نویسنده سایت'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='شناسه یکتا'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_version',
            field=models.CharField(default='1.0.0', max_length=20, verbose_name='نسخه سایت'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_title',
            field=models.CharField(default='راه‌حل جامع برای تمام نیازهای مالی و حقوقی شما', max_length=200, verbose_name='عنوان هرو'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/', verbose_name='تصویر هرو'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_icon',
            field=models.CharField(default='🏛️', max_length=50, verbose_name='آیکون هرو'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='services_background_color',
            field=models.CharField(default='#f8f9fa', max_length=20, verbose_name='رنگ پس‌زمینه خدمات'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service_loan_icon',
            field=models.CharField(default='💰', max_length=50, verbose_name='آیکون خدمات وام'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service_loan_image',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='تصویر خدمات وام'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service_leasing_icon',
            field=models.CharField(default='🚗', max_length=50, verbose_name='آیکون خدمات لیزینگ'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service_leasing_image',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='تصویر خدمات لیزینگ'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service_registration_icon',
            field=models.CharField(default='🏢', max_length=50, verbose_name='آیکون خدمات ثبت شرکت'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service_registration_image',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='تصویر خدمات ثبت شرکت'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service_legal_icon',
            field=models.CharField(default='⚖️', max_length=50, verbose_name='آیکون خدمات حقوقی'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service_legal_image',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='تصویر خدمات حقوقی'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service_licenses_icon',
            field=models.CharField(default='📜', max_length=50, verbose_name='آیکون خدمات ثبت مجوزها'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service_licenses_image',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='تصویر خدمات ثبت مجوزها'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service_commercial_icon',
            field=models.CharField(default='💼', max_length=50, verbose_name='آیکون خدمات کارت بازرگانی'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service_commercial_image',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='تصویر خدمات کارت بازرگانی'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='loan_mortgage_icon',
            field=models.CharField(default='🏠', max_length=50, verbose_name='آیکون وام مسکن'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='loan_mortgage_image',
            field=models.ImageField(blank=True, null=True, upload_to='loans/', verbose_name='تصویر وام مسکن'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='loan_car_icon',
            field=models.CharField(default='🚗', max_length=50, verbose_name='آیکون وام خودرو'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='loan_car_image',
            field=models.ImageField(blank=True, null=True, upload_to='loans/', verbose_name='تصویر وام خودرو'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='loan_business_icon',
            field=models.CharField(default='💼', max_length=50, verbose_name='آیکون وام کسب‌وکار'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='loan_business_image',
            field=models.ImageField(blank=True, null=True, upload_to='loans/', verbose_name='تصویر وام کسب‌وکار'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='loan_investment_icon',
            field=models.CharField(default='📊', max_length=50, verbose_name='آیکون وام سرمایه‌گذاری'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='loan_investment_image',
            field=models.ImageField(blank=True, null=True, upload_to='loans/', verbose_name='تصویر وام سرمایه‌گذاری'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='leasing_image',
            field=models.ImageField(blank=True, null=True, upload_to='leasing/', verbose_name='تصویر لیزینگ'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='leasing_background_color',
            field=models.CharField(default='#1a365d', max_length=20, verbose_name='رنگ پس‌زمینه لیزینگ'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='registration_company_icon',
            field=models.CharField(default='🏢', max_length=50, verbose_name='آیکون ثبت شرکت'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='registration_company_image',
            field=models.ImageField(blank=True, null=True, upload_to='registration/', verbose_name='تصویر ثبت شرکت'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='registration_license_icon',
            field=models.CharField(default='📜', max_length=50, verbose_name='آیکون اخذ مجوزها'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='registration_license_image',
            field=models.ImageField(blank=True, null=True, upload_to='registration/', verbose_name='تصویر اخذ مجوزها'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='registration_commercial_icon',
            field=models.CharField(default='💼', max_length=50, verbose_name='آیکون کارت بازرگانی'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='registration_commercial_image',
            field=models.ImageField(blank=True, null=True, upload_to='registration/', verbose_name='تصویر کارت بازرگانی'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='process_background_color',
            field=models.CharField(default='#ffffff', max_length=20, verbose_name='رنگ پس‌زمینه فرآیند'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='process_step_1_icon',
            field=models.CharField(default='📞', max_length=50, verbose_name='آیکون مرحله ۱'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='process_step_1_number',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='شماره مرحله ۱'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='process_step_2_icon',
            field=models.CharField(default='🔍', max_length=50, verbose_name='آیکون مرحله ۲'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='process_step_2_number',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='شماره مرحله ۲'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='process_step_3_icon',
            field=models.CharField(default='⚙️', max_length=50, verbose_name='آیکون مرحله ۳'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='process_step_3_number',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='شماره مرحله ۳'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='process_step_4_icon',
            field=models.CharField(default='✅', max_length=50, verbose_name='آیکون مرحله ۴'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='process_step_4_number',
            field=models.PositiveSmallIntegerField(default=4, verbose_name='شماره مرحله ۴'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='features_background_color',
            field=models.CharField(default='#f8f9fa', max_length=20, verbose_name='رنگ پس‌زمینه ویژگی‌ها'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='feature_1_icon',
            field=models.CharField(default='⭐', max_length=50, verbose_name='آیکون ویژگی ۱'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='feature_2_icon',
            field=models.CharField(default='💰', max_length=50, verbose_name='آیکون ویژگی ۲'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='feature_3_icon',
            field=models.CharField(default='⚡', max_length=50, verbose_name='آیکون ویژگی ۳'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='feature_4_icon',
            field=models.CharField(default='🔐', max_length=50, verbose_name='آیکون ویژگی ۴'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='feature_5_icon',
            field=models.CharField(default='🕐', max_length=50, verbose_name='آیکون ویژگی ۵'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='feature_6_icon',
            field=models.CharField(default='💻', max_length=50, verbose_name='آیکون ویژگی ۶'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='feature_7_icon',
            field=models.CharField(default='📊', max_length=50, verbose_name='آیکون ویژگی ۷'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='feature_8_icon',
            field=models.CharField(default='🎯', max_length=50, verbose_name='آیکون ویژگی ۸'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='comparison_background_color',
            field=models.CharField(default='#ffffff', max_length=20, verbose_name='رنگ پس‌زمینه مقایسه'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='trust_background_color',
            field=models.CharField(default='#1a365d', max_length=20, verbose_name='رنگ پس‌زمینه اعتماد'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='trust_stat_1_icon',
            field=models.CharField(default='👥', max_length=50, verbose_name='آیکون آمار ۱ اعتماد'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='trust_stat_2_icon',
            field=models.CharField(default='⭐', max_length=50, verbose_name='آیکون آمار ۲ اعتماد'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='trust_stat_3_icon',
            field=models.CharField(default='🏆', max_length=50, verbose_name='آیکون آمار ۳ اعتماد'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='trust_stat_4_icon',
            field=models.CharField(default='💼', max_length=50, verbose_name='آیکون آمار ۴ اعتماد'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='trust_stat_5_icon',
            field=models.CharField(default='📊', max_length=50, verbose_name='آیکون آمار ۵ اعتماد'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='trust_stat_6_icon',
            field=models.CharField(default='⚡', max_length=50, verbose_name='آیکون آمار ۶ اعتماد'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='testimonials_background_color',
            field=models.CharField(default='#ffffff', max_length=20, verbose_name='رنگ پس‌زمینه نظرات'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='testimonial_1_rating',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='امتیاز نظر ۱'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='testimonial_1_image',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='تصویر نظر ۱'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='testimonial_2_rating',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='امتیاز نظر ۲'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='testimonial_2_image',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='تصویر نظر ۲'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='testimonial_3_rating',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='امتیاز نظر ۳'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='testimonial_3_image',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='تصویر نظر ۳'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='faq_background_color',
            field=models.CharField(default='#f8f9fa', max_length=20, verbose_name='رنگ پس‌زمینه سوالات متداول'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='faq_1_icon',
            field=models.CharField(default='❓', max_length=50, verbose_name='آیکون سؤال ۱'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='faq_2_icon',
            field=models.CharField(default='❓', max_length=50, verbose_name='آیکون سؤال ۲'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='faq_3_icon',
            field=models.CharField(default='❓', max_length=50, verbose_name='آیکون سؤال ۳'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='faq_4_icon',
            field=models.CharField(default='❓', max_length=50, verbose_name='آیکون سؤال ۴'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='faq_5_icon',
            field=models.CharField(default='❓', max_length=50, verbose_name='آیکون سؤال ۵'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='faq_6_icon',
            field=models.CharField(default='❓', max_length=50, verbose_name='آیکون سؤال ۶'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_background_color',
            field=models.CharField(default='#d4af37', max_length=20, verbose_name='رنگ پس‌زمینه دعوت به عمل'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_button_1_text',
            field=models.CharField(default='📞 تماس با ما', max_length=50, verbose_name='متن دکمه ۱ دعوت به عمل'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_button_1_icon',
            field=models.CharField(default='📞', max_length=50, verbose_name='آیکون دکمه ۱ دعوت به عمل'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_button_2_text',
            field=models.CharField(default='📋 مشاهده خدمات', max_length=50, verbose_name='متن دکمه ۲ دعوت به عمل'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_button_2_icon',
            field=models.CharField(default='📋', max_length=50, verbose_name='آیکون دکمه ۲ دعوت به عمل'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_background_color',
            field=models.CharField(default='#ffffff', max_length=20, verbose_name='رنگ پس‌زمینه تماس'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_phone_icon',
            field=models.CharField(default='📞', max_length=50, verbose_name='آیکون تلفن تماس'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_email_title',
            field=models.CharField(default='ایمیل', max_length=100, verbose_name='عنوان ایمیل'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(default='info@shahrar.ir', max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_email_icon',
            field=models.CharField(default='✉️', max_length=50, verbose_name='آیکون ایمیل'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_address_icon',
            field=models.CharField(default='📍', max_length=50, verbose_name='آیکون آدرس'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_hours_icon',
            field=models.CharField(default='🕐', max_length=50, verbose_name='آیکون ساعات کاری'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_background_color',
            field=models.CharField(default='#0f1c2e', max_length=20, verbose_name='رنگ پس‌زمینه فوتر'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_instagram_url',
            field=models.URLField(blank=True, null=True, verbose_name='لینک اینستاگرام'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_telegram_url',
            field=models.URLField(blank=True, null=True, verbose_name='لینک تلگرام'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_linkedin_url',
            field=models.URLField(blank=True, null=True, verbose_name='لینک لینکدین'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_twitter_url',
            field=models.URLField(blank=True, null=True, verbose_name='لینک توییتر'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
    ]