# Generated by Django 5.2.7 on 2025-11-01 21:52

from django.db import migrations, models
import django.utils.timezone
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_sitesettings_comparison_subtitle_and_more'),
    ]

    operations = [
        # Split the large migration into smaller chunks to avoid MySQL row size limit
        
        # First, add the most essential fields
        migrations.AddField(
            model_name='sitesettings',
            name='site_uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='شناسه یکتا'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        
        # Add social media fields
        migrations.AddField(
            model_name='sitesettings',
            name='social_instagram_url',
            field=models.URLField(blank=True, null=True, verbose_name='لینک اینستاگرام'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_telegram_url',
            field=models.URLField(blank=True, null=True, verbose_name='لینک تلگرام'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_linkedin_url',
            field=models.URLField(blank=True, null=True, verbose_name='لینک لینکدین'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_twitter_url',
            field=models.URLField(blank=True, null=True, verbose_name='لینک توییتر'),
        ),
        
        # Add hero section fields
        migrations.AddField(
            model_name='sitesettings',
            name='hero_title',
            field=models.CharField(default='راه‌حل جامع برای تمام نیازهای مالی و حقوقی شما', max_length=200, verbose_name='عنوان هرو'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_icon',
            field=models.CharField(default='🏛️', max_length=50, verbose_name='آیکون هرو'),
        ),
        
        # Add service related fields
        migrations.AddField(
            model_name='sitesettings',
            name='services_background_color',
            field=models.CharField(default='#f8f9fa', max_length=20, verbose_name='رنگ پس‌زمینه خدمات'),
        ),
        
        # Add site metadata fields
        migrations.AddField(
            model_name='sitesettings',
            name='site_keywords',
            field=models.TextField(default='خرید وام, فروش وام, لیزینگ خودرو, ثبت شرکت, خدمات حقوقی, وکالت, ثبت مجوز', verbose_name='کلمات کلیدی'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_author',
            field=models.CharField(default='Shahrar Financial & Legal Services', max_length=100, verbose_name='نویسنده سایت'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_version',
            field=models.CharField(default='1.0.0', max_length=20, verbose_name='نسخه سایت'),
        ),
    ]