# Generated by Django 5.2.7 on 2025-11-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0002_collaborationprocess_collaborationstep"),
    ]

    operations = [
        migrations.AddField(
            model_name="leasingoffer",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="leasing/", verbose_name="تصویر لیزینگ"
            ),
        ),
    ]
