# Generated by Django 5.2.8 on 2025-11-28 15:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0003_leasingoffer_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="شرکت", max_length=150, verbose_name="نام شرکت"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        upload_to="company_logos/", verbose_name="لوگو شرکت"
                    ),
                ),
                ("link", models.URLField(default="#", verbose_name="لینک شرکت")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ترتیب")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاریخ ایجاد"
                    ),
                ),
            ],
            options={
                "verbose_name": "شرکت",
                "verbose_name_plural": "شرکت\u200cها",
                "ordering": ["order"],
            },
        ),
    ]
