# Generated by Django 4.2.7 on 2025-11-02 10:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0005_category_comparison_contactform_contactinfo_faq_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "verbose_name": "دسته\u200cبندی",
                "verbose_name_plural": "دسته\u200cبندی\u200cها",
            },
        ),
        migrations.AlterModelOptions(
            name="comparison",
            options={"verbose_name": "مقایسه", "verbose_name_plural": "مقایسه\u200cها"},
        ),
        migrations.AlterModelOptions(
            name="contactform",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "فرم تماس",
                "verbose_name_plural": "فرم\u200cهای تماس",
            },
        ),
        migrations.AlterModelOptions(
            name="contactinfo",
            options={
                "verbose_name": "اطلاعات تماس",
                "verbose_name_plural": "اطلاعات تماس",
            },
        ),
        migrations.AlterModelOptions(
            name="faq",
            options={
                "ordering": ["order"],
                "verbose_name": "سؤال متداول",
                "verbose_name_plural": "سؤالات متداول",
            },
        ),
        migrations.AlterModelOptions(
            name="herosection",
            options={"verbose_name": "بخش هرو", "verbose_name_plural": "بخش هرو"},
        ),
        migrations.AlterModelOptions(
            name="leasingoffer",
            options={
                "verbose_name": "پیشنهاد لیزینگ",
                "verbose_name_plural": "پیشنهادات لیزینگ",
            },
        ),
        migrations.AlterModelOptions(
            name="loancategory",
            options={
                "ordering": ["order"],
                "verbose_name": "دسته\u200cبندی وام",
                "verbose_name_plural": "دسته\u200cبندی وام\u200cها",
            },
        ),
        migrations.AlterModelOptions(
            name="loanitem",
            options={
                "verbose_name": "آیتم وام",
                "verbose_name_plural": "آیتم\u200cهای وام",
            },
        ),
        migrations.AlterModelOptions(
            name="service",
            options={
                "ordering": ["order"],
                "verbose_name": "خدمات",
                "verbose_name_plural": "خدمات",
            },
        ),
        migrations.AlterModelOptions(
            name="serviceitem",
            options={
                "verbose_name": "آیتم خدمات",
                "verbose_name_plural": "آیتم\u200cهای خدمات",
            },
        ),
        migrations.AlterModelOptions(
            name="sitesettings",
            options={
                "verbose_name": "تنظیمات سایت",
                "verbose_name_plural": "تنظیمات سایت",
            },
        ),
        migrations.AlterModelOptions(
            name="statistic",
            options={
                "ordering": ["order"],
                "verbose_name": "آمار",
                "verbose_name_plural": "آمارها",
            },
        ),
        migrations.AlterModelOptions(
            name="testimonial",
            options={
                "verbose_name": "نظر مشتری",
                "verbose_name_plural": "نظرات مشتریان",
            },
        ),
        migrations.AlterModelOptions(
            name="whyusfeature",
            options={
                "ordering": ["order"],
                "verbose_name": "ویژگی ما",
                "verbose_name_plural": "ویژگی\u200cهای ما",
            },
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(
                default="توضیحات دسته\u200cبندی", verbose_name="توضیحات"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.CharField(default="📂", max_length=50, verbose_name="آیکون"),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                default="دسته\u200cبندی", max_length=100, verbose_name="نام"
            ),
        ),
        migrations.AlterField(
            model_name="comparison",
            name="criterion",
            field=models.CharField(
                default="معیار", max_length=100, verbose_name="معیار"
            ),
        ),
        migrations.AlterField(
            model_name="comparison",
            name="others_value",
            field=models.CharField(
                default="مقدار دیگران", max_length=100, verbose_name="مقدار دیگران"
            ),
        ),
        migrations.AlterField(
            model_name="comparison",
            name="our_value",
            field=models.CharField(
                default="مقدار ما", max_length=100, verbose_name="مقدار ما"
            ),
        ),
        migrations.AlterField(
            model_name="contactform",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="تاریخ ایجاد"
            ),
        ),
        migrations.AlterField(
            model_name="contactform",
            name="email",
            field=models.EmailField(
                default="email@example.com", max_length=254, verbose_name="ایمیل"
            ),
        ),
        migrations.AlterField(
            model_name="contactform",
            name="message",
            field=models.TextField(default="پیام", verbose_name="پیام"),
        ),
        migrations.AlterField(
            model_name="contactform",
            name="name",
            field=models.CharField(default="نام", max_length=100, verbose_name="نام"),
        ),
        migrations.AlterField(
            model_name="contactform",
            name="phone",
            field=models.CharField(
                default="021-1234-5678", max_length=20, verbose_name="تلفن"
            ),
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="address",
            field=models.TextField(default="تهران، ایران", verbose_name="آدرس"),
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="email",
            field=models.EmailField(
                default="info@shahreraze.com", max_length=254, verbose_name="ایمیل"
            ),
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="map_embed",
            field=models.TextField(blank=True, default="", verbose_name="کد نقشه"),
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="phone",
            field=models.CharField(
                default="021-1234-5678", max_length=20, verbose_name="تلفن"
            ),
        ),
        migrations.AlterField(
            model_name="faq",
            name="answer",
            field=models.TextField(default="پاسخ", verbose_name="پاسخ"),
        ),
        migrations.AlterField(
            model_name="faq",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="فعال"),
        ),
        migrations.AlterField(
            model_name="faq",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="ترتیب"),
        ),
        migrations.AlterField(
            model_name="faq",
            name="question",
            field=models.CharField(default="سؤال", max_length=200, verbose_name="سؤال"),
        ),
        migrations.AlterField(
            model_name="herosection",
            name="background_image",
            field=models.ImageField(
                blank=True, upload_to="hero/", verbose_name="تصویر پس\u200cزمینه"
            ),
        ),
        migrations.AlterField(
            model_name="herosection",
            name="cta_primary_link",
            field=models.URLField(default="#contact", verbose_name="لینک دکمه اصلی"),
        ),
        migrations.AlterField(
            model_name="herosection",
            name="cta_primary_text",
            field=models.CharField(
                default="تماس با ما", max_length=100, verbose_name="متن دکمه اصلی"
            ),
        ),
        migrations.AlterField(
            model_name="herosection",
            name="cta_secondary_link",
            field=models.URLField(default="#services", verbose_name="لینک دکمه ثانویه"),
        ),
        migrations.AlterField(
            model_name="herosection",
            name="cta_secondary_text",
            field=models.CharField(
                default="مشاهده خدمات", max_length=100, verbose_name="متن دکمه ثانویه"
            ),
        ),
        migrations.AlterField(
            model_name="herosection",
            name="headline",
            field=models.CharField(
                default="خدمات مالی و حقوقی جامع", max_length=200, verbose_name="عنوان"
            ),
        ),
        migrations.AlterField(
            model_name="herosection",
            name="subheadline",
            field=models.TextField(
                default="خدمات حرفه\u200cای برای تمام نیازهای مالی و حقوقی شما",
                verbose_name="زیرعنوان",
            ),
        ),
        migrations.AlterField(
            model_name="leasingoffer",
            name="description",
            field=models.TextField(
                default="توضیحات پیشنهاد لیزینگ", verbose_name="توضیحات"
            ),
        ),
        migrations.AlterField(
            model_name="leasingoffer",
            name="features",
            field=models.TextField(
                default="ویژگی 1\nویژگی 2\nویژگی 3",
                help_text="هر ویژگی را در یک خط وارد کنید",
                verbose_name="ویژگی\u200cها",
            ),
        ),
        migrations.AlterField(
            model_name="leasingoffer",
            name="stats",
            field=models.TextField(
                default="قیمت:10000\nمدت:24 ماه",
                help_text="آمارها را به فرمت: برچسب:مقدار (در هر خط یکی) وارد کنید",
                verbose_name="آمارها",
            ),
        ),
        migrations.AlterField(
            model_name="leasingoffer",
            name="title",
            field=models.CharField(
                default="لیزینگ خودرو", max_length=100, verbose_name="عنوان"
            ),
        ),
        migrations.AlterField(
            model_name="loancategory",
            name="description",
            field=models.TextField(
                default="توضیحات دسته\u200cبندی وام", verbose_name="توضیحات"
            ),
        ),
        migrations.AlterField(
            model_name="loancategory",
            name="icon",
            field=models.CharField(default="💰", max_length=50, verbose_name="آیکون"),
        ),
        migrations.AlterField(
            model_name="loancategory",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="ترتیب"),
        ),
        migrations.AlterField(
            model_name="loancategory",
            name="title",
            field=models.CharField(
                default="دسته\u200cبندی وام", max_length=100, verbose_name="عنوان"
            ),
        ),
        migrations.AlterField(
            model_name="loanitem",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="website.loancategory",
                verbose_name="دسته\u200cبندی",
            ),
        ),
        migrations.AlterField(
            model_name="loanitem",
            name="description",
            field=models.TextField(default="توضیحات آیتم وام", verbose_name="توضیحات"),
        ),
        migrations.AlterField(
            model_name="loanitem",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="فعال"),
        ),
        migrations.AlterField(
            model_name="loanitem",
            name="title",
            field=models.CharField(
                default="آیتم وام", max_length=100, verbose_name="عنوان"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="content",
            field=models.TextField(default="محتوای کامل خدمات", verbose_name="محتوا"),
        ),
        migrations.AlterField(
            model_name="service",
            name="icon",
            field=models.CharField(default="🔧", max_length=50, verbose_name="آیکون"),
        ),
        migrations.AlterField(
            model_name="service",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="فعال"),
        ),
        migrations.AlterField(
            model_name="service",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="ترتیب"),
        ),
        migrations.AlterField(
            model_name="service",
            name="short_description",
            field=models.TextField(
                default="توضیحات خدمات", verbose_name="توضیحات کوتاه"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="title",
            field=models.CharField(
                default="خدمات", max_length=100, verbose_name="عنوان"
            ),
        ),
        migrations.AlterField(
            model_name="serviceitem",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="website.category",
                verbose_name="دسته\u200cبندی",
            ),
        ),
        migrations.AlterField(
            model_name="serviceitem",
            name="cta_link",
            field=models.URLField(default="#", verbose_name="لینک دکمه عملیات"),
        ),
        migrations.AlterField(
            model_name="serviceitem",
            name="cta_text",
            field=models.CharField(
                default="اطلاعات بیشتر", max_length=100, verbose_name="متن دکمه عملیات"
            ),
        ),
        migrations.AlterField(
            model_name="serviceitem",
            name="description",
            field=models.TextField(
                default="توضیحات آیتم خدمات", verbose_name="توضیحات"
            ),
        ),
        migrations.AlterField(
            model_name="serviceitem",
            name="title",
            field=models.CharField(
                default="آیتم خدمات", max_length=100, verbose_name="عنوان"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="address",
            field=models.TextField(default="تهران، ایران", verbose_name="آدرس"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="description",
            field=models.TextField(
                default="خدمات مالی و حقوقی تخصصی", verbose_name="توضیحات"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="email_main",
            field=models.EmailField(
                default="info@shahreraze.com", max_length=254, verbose_name="ایمیل اصلی"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="email_support",
            field=models.EmailField(
                default="support@shahreraze.com",
                max_length=254,
                verbose_name="ایمیل پشتیبانی",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="favicon",
            field=models.ImageField(
                blank=True, upload_to="favicons/", verbose_name="آیکون"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="footer_text",
            field=models.TextField(
                default="© 2025 شهر راز. تمامی حقوق محفوظ است.", verbose_name="متن فوتر"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="logo",
            field=models.ImageField(
                blank=True, upload_to="logos/", verbose_name="لوگو"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="meta_description",
            field=models.TextField(blank=True, default="", verbose_name="توضیحات متا"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="meta_keywords",
            field=models.TextField(
                blank=True, default="", verbose_name="کلمات کلیدی متا"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="phone_alt",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="تلفن جایگزین"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="phone_main",
            field=models.CharField(
                default="021-1234-5678", max_length=20, verbose_name="تلفن اصلی"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="site_name",
            field=models.CharField(
                default="شهر راز", max_length=100, verbose_name="نام سایت"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="work_hours",
            field=models.CharField(
                default="شنبه-پنجشنبه: 9صبح-6عصر",
                max_length=100,
                verbose_name="ساعات کاری",
            ),
        ),
        migrations.AlterField(
            model_name="statistic",
            name="icon",
            field=models.CharField(default="👥", max_length=50, verbose_name="آیکون"),
        ),
        migrations.AlterField(
            model_name="statistic",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="ترتیب"),
        ),
        migrations.AlterField(
            model_name="statistic",
            name="title",
            field=models.CharField(
                default="مشتریان", max_length=100, verbose_name="عنوان"
            ),
        ),
        migrations.AlterField(
            model_name="statistic",
            name="value",
            field=models.IntegerField(default=100, verbose_name="مقدار"),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="client_name",
            field=models.CharField(
                default="مشتری", max_length=100, verbose_name="نام مشتری"
            ),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="client_role",
            field=models.CharField(
                default="نقش مشتری", max_length=100, verbose_name="نقش مشتری"
            ),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="comment",
            field=models.TextField(default="نظر مشتری", verbose_name="نظر"),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="photo",
            field=models.ImageField(
                blank=True, upload_to="testimonials/", verbose_name="تصویر"
            ),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="rating",
            field=models.IntegerField(
                choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                default=5,
                verbose_name="امتیاز",
            ),
        ),
        migrations.AlterField(
            model_name="whyusfeature",
            name="description",
            field=models.TextField(default="توضیحات ویژگی", verbose_name="توضیحات"),
        ),
        migrations.AlterField(
            model_name="whyusfeature",
            name="icon",
            field=models.CharField(default="⭐", max_length=50, verbose_name="آیکون"),
        ),
        migrations.AlterField(
            model_name="whyusfeature",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="ترتیب"),
        ),
        migrations.AlterField(
            model_name="whyusfeature",
            name="title",
            field=models.CharField(
                default="ویژگی", max_length=100, verbose_name="عنوان"
            ),
        ),
    ]
