# Generated by Django 4.2.7 on 2025-11-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0006_alter_category_options_alter_comparison_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="branch_office_address",
            field=models.TextField(blank=True, default="", verbose_name="آدرس شعبه"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="head_office_address",
            field=models.TextField(
                default="تهران، خیابان آزادی، پلاک ۱۲۳", verbose_name="آدرس دفتر مرکزی"
            ),
        ),
    ]
