# Generated by Django 4.2.7 on 2025-11-03 11:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0007_sitesettings_branch_office_address_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ContactForm",
        ),
        migrations.AddField(
            model_name="testimonial",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="تاریخ ایجاد"
            ),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "در حال بررسی"),
                    ("approved", "تایید شده"),
                    ("rejected", "رد شده"),
                ],
                default="pending",
                max_length=20,
                verbose_name="وضعیت",
            ),
        ),
    ]
