# Generated by Django 4.2.7 on 2025-11-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0008_delete_contactform_testimonial_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="static_footer_text",
            field=models.TextField(
                default="طراحی شده با ❤ | Desigend by H0lwin",
                help_text="این متن در پایین فوتر نمایش داده می\u200cشود و تغییر نمی\u200cکند",
                verbose_name="متن فوتر ثابت",
            ),
        ),
    ]
