# Generated by Django 4.2.7 on 2025-11-03 13:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0009_sitesettings_static_footer_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitesettings",
            name="static_footer_text",
        ),
    ]
