# Generated by Django 5.2.7 on 2025-11-03

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_remove_sitesettings_static_footer_text'),
    ]

    operations = [
        # This migration is intentionally left empty to skip the problematic migration 0003
        # The fields that were supposed to be added in migration 0003 will be added in a more
        # structured way in future migrations, avoiding the MySQL row size limit issue.
    ]