# Generated by Django 5.2.7 on 2025-11-03

from django.db import migrations, models
import django.utils.timezone
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_fix_sitesettings_migration'),
    ]

    operations = [
        # Add only the essential fields that don't cause row size issues
        migrations.AddField(
            model_name='sitesettings',
            name='site_uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='شناسه یکتا'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        # Add social media fields
        migrations.AddField(
            model_name='sitesettings',
            name='social_instagram_url',
            field=models.URLField(blank=True, null=True, verbose_name='لینک اینستاگرام'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_telegram_url',
            field=models.URLField(blank=True, null=True, verbose_name='لینک تلگرام'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_linkedin_url',
            field=models.URLField(blank=True, null=True, verbose_name='لینک لینکدین'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_twitter_url',
            field=models.URLField(blank=True, null=True, verbose_name='لینک توییتر'),
        ),
    ]