# Generated by Django 5.2.7 on 2025-11-03

from django.db import migrations, models, connection
import django.utils.timezone
import uuid

def check_and_add_fields(apps, schema_editor):
    SiteSettings = apps.get_model('website', 'SiteSettings')
    db_alias = schema_editor.connection.alias
    
    # Check if columns already exist
    cursor = connection.cursor()
    cursor.execute("""
        SELECT COLUMN_NAME 
        FROM INFORMATION_SCHEMA.COLUMNS 
        WHERE TABLE_SCHEMA = DATABASE() 
        AND TABLE_NAME = 'website_sitesettings'
    """)
    
    existing_columns = [row[0] for row in cursor.fetchall()]
    
    # Fields we want to add
    fields_to_add = {
        'site_uuid': models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='شناسه یکتا'),
        'created_at': models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد'),
        'updated_at': models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        'social_instagram_url': models.URLField(blank=True, null=True, verbose_name='لینک اینستاگرام'),
        'social_telegram_url': models.URLField(blank=True, null=True, verbose_name='لینک تلگرام'),
        'social_linkedin_url': models.URLField(blank=True, null=True, verbose_name='لینک لینکدین'),
        'social_twitter_url': models.URLField(blank=True, null=True, verbose_name='لینک توییتر'),
    }
    
    # Only add fields that don't already exist
    for field_name, field in fields_to_add.items():
        if field_name not in existing_columns:
            schema_editor.add_field(SiteSettings, field)

class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_add_sitesettings_fields_properly'),
    ]

    operations = [
        migrations.RunPython(check_and_add_fields, reverse_code=migrations.RunPython.noop),
    ]