# Generated by Django 5.2.7 on 2025-11-03

from django.db import migrations, models
import django.utils.timezone
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_handle_existing_fields'),
    ]

    operations = [
        # This migration replaces the problematic 0003 migration by splitting it into smaller parts
        # Add remaining service icon fields
        migrations.AddField(
            model_name='sitesettings',
            name='service_loan_icon',
            field=models.CharField(default='💰', max_length=50, verbose_name='آیکون خدمات وام'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service_leasing_icon',
            field=models.CharField(default='🚗', max_length=50, verbose_name='آیکون خدمات لیزینگ'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service_registration_icon',
            field=models.CharField(default='🏢', max_length=50, verbose_name='آیکون خدمات ثبت شرکت'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service_legal_icon',
            field=models.CharField(default='⚖️', max_length=50, verbose_name='آیکون خدمات حقوقی'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service_licenses_icon',
            field=models.CharField(default='📜', max_length=50, verbose_name='آیکون خدمات ثبت مجوزها'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service_commercial_icon',
            field=models.CharField(default='💼', max_length=50, verbose_name='آیکون خدمات کارت بازرگانی'),
        ),
    ]