# Generated by Django 5.2.7 on 2025-11-03

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_split_large_migration'),
    ]

    operations = [
        # Continue adding the remaining fields from the original large migration
        # Add loan related fields
        migrations.AddField(
            model_name='sitesettings',
            name='loan_mortgage_icon',
            field=models.CharField(default='🏠', max_length=50, verbose_name='آیکون وام مسکن'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='loan_car_icon',
            field=models.CharField(default='🚗', max_length=50, verbose_name='آیکون وام خودرو'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='loan_business_icon',
            field=models.CharField(default='💼', max_length=50, verbose_name='آیکون وام کسب‌وکار'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='loan_investment_icon',
            field=models.CharField(default='📊', max_length=50, verbose_name='آیکون وام سرمایه‌گذاری'),
        ),
        # Add leasing fields
        migrations.AddField(
            model_name='sitesettings',
            name='leasing_background_color',
            field=models.CharField(default='#1a365d', max_length=20, verbose_name='رنگ پس‌زمینه لیزینگ'),
        ),
        # Add registration fields
        migrations.AddField(
            model_name='sitesettings',
            name='registration_company_icon',
            field=models.CharField(default='🏢', max_length=50, verbose_name='آیکون ثبت شرکت'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='registration_license_icon',
            field=models.CharField(default='📜', max_length=50, verbose_name='آیکون اخذ مجوزها'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='registration_commercial_icon',
            field=models.CharField(default='💼', max_length=50, verbose_name='آیکون کارت بازرگانی'),
        ),
    ]