# Generated by Django 5.2.7 on 2025-11-03

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_split_large_migration_part2'),
    ]

    operations = [
        # Final part of the split migration
        # Add process fields
        migrations.AddField(
            model_name='sitesettings',
            name='process_background_color',
            field=models.CharField(default='#ffffff', max_length=20, verbose_name='رنگ پس‌زمینه فرآیند'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='process_step_1_icon',
            field=models.CharField(default='📞', max_length=50, verbose_name='آیکون مرحله ۱'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='process_step_2_icon',
            field=models.CharField(default='🔍', max_length=50, verbose_name='آیکون مرحله ۲'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='process_step_3_icon',
            field=models.CharField(default='⚙️', max_length=50, verbose_name='آیکون مرحله ۳'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='process_step_4_icon',
            field=models.CharField(default='✅', max_length=50, verbose_name='آیکون مرحله ۴'),
        ),
        # Add feature fields
        migrations.AddField(
            model_name='sitesettings',
            name='features_background_color',
            field=models.CharField(default='#f8f9fa', max_length=20, verbose_name='رنگ پس‌زمینه ویژگی‌ها'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='feature_1_icon',
            field=models.CharField(default='⭐', max_length=50, verbose_name='آیکون ویژگی ۱'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='feature_2_icon',
            field=models.CharField(default='💰', max_length=50, verbose_name='آیکون ویژگی ۲'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='feature_3_icon',
            field=models.CharField(default='⚡', max_length=50, verbose_name='آیکون ویژگی ۳'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='feature_4_icon',
            field=models.CharField(default='🔐', max_length=50, verbose_name='آیکون ویژگی ۴'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='feature_5_icon',
            field=models.CharField(default='🕐', max_length=50, verbose_name='آیکون ویژگی ۵'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='feature_6_icon',
            field=models.CharField(default='💻', max_length=50, verbose_name='آیکون ویژگی ۶'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='feature_7_icon',
            field=models.CharField(default='📊', max_length=50, verbose_name='آیکون ویژگی ۷'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='feature_8_icon',
            field=models.CharField(default='🎯', max_length=50, verbose_name='آیکون ویژگی ۸'),
        ),
    ]