# Generated by Django 5.2.7 on 2025-11-03

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_split_large_migration_part3'),
    ]

    operations = [
        # Final part of the split migration
        # Add comparison and trust fields
        migrations.AddField(
            model_name='sitesettings',
            name='comparison_background_color',
            field=models.CharField(default='#ffffff', max_length=20, verbose_name='رنگ پس‌زمینه مقایسه'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='trust_background_color',
            field=models.CharField(default='#1a365d', max_length=20, verbose_name='رنگ پس‌زمینه اعتماد'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='trust_stat_1_icon',
            field=models.CharField(default='👥', max_length=50, verbose_name='آیکون آمار ۱ اعتماد'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='trust_stat_2_icon',
            field=models.CharField(default='⭐', max_length=50, verbose_name='آیکون آمار ۲ اعتماد'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='trust_stat_3_icon',
            field=models.CharField(default='🏆', max_length=50, verbose_name='آیکون آمار ۳ اعتماد'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='trust_stat_4_icon',
            field=models.CharField(default='💼', max_length=50, verbose_name='آیکون آمار ۴ اعتماد'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='trust_stat_5_icon',
            field=models.CharField(default='📊', max_length=50, verbose_name='آیکون آمار ۵ اعتماد'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='trust_stat_6_icon',
            field=models.CharField(default='⚡', max_length=50, verbose_name='آیکون آمار ۶ اعتماد'),
        ),
        # Add testimonials fields
        migrations.AddField(
            model_name='sitesettings',
            name='testimonials_background_color',
            field=models.CharField(default='#ffffff', max_length=20, verbose_name='رنگ پس‌زمینه نظرات'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='testimonial_1_rating',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='امتیاز نظر ۱'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='testimonial_2_rating',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='امتیاز نظر ۲'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='testimonial_3_rating',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='امتیاز نظر ۳'),
        ),
        # Add FAQ fields
        migrations.AddField(
            model_name='sitesettings',
            name='faq_background_color',
            field=models.CharField(default='#f8f9fa', max_length=20, verbose_name='رنگ پس‌زمینه سوالات متداول'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='faq_1_icon',
            field=models.CharField(default='❓', max_length=50, verbose_name='آیکون سؤال ۱'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='faq_2_icon',
            field=models.CharField(default='❓', max_length=50, verbose_name='آیکون سؤال ۲'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='faq_3_icon',
            field=models.CharField(default='❓', max_length=50, verbose_name='آیکون سؤال ۳'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='faq_4_icon',
            field=models.CharField(default='❓', max_length=50, verbose_name='آیکون سؤال ۴'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='faq_5_icon',
            field=models.CharField(default='❓', max_length=50, verbose_name='آیکون سؤال ۵'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='faq_6_icon',
            field=models.CharField(default='❓', max_length=50, verbose_name='آیکون سؤال ۶'),
        ),
        # Add CTA fields
        migrations.AddField(
            model_name='sitesettings',
            name='cta_background_color',
            field=models.CharField(default='#d4af37', max_length=20, verbose_name='رنگ پس‌زمینه دعوت به عمل'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_button_1_text',
            field=models.CharField(default='📞 تماس با ما', max_length=50, verbose_name='متن دکمه ۱ دعوت به عمل'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_button_1_icon',
            field=models.CharField(default='📞', max_length=50, verbose_name='آیکون دکمه ۱ دعوت به عمل'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_button_2_text',
            field=models.CharField(default='📋 مشاهده خدمات', max_length=50, verbose_name='متن دکمه ۲ دعوت به عمل'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_button_2_icon',
            field=models.CharField(default='📋', max_length=50, verbose_name='آیکون دکمه ۲ دعوت به عمل'),
        ),
        # Add contact fields
        migrations.AddField(
            model_name='sitesettings',
            name='contact_background_color',
            field=models.CharField(default='#ffffff', max_length=20, verbose_name='رنگ پس‌زمینه تماس'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_phone_icon',
            field=models.CharField(default='📞', max_length=50, verbose_name='آیکون تلفن تماس'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_email_title',
            field=models.CharField(default='ایمیل', max_length=100, verbose_name='عنوان ایمیل'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(default='info@shahrar.ir', max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_email_icon',
            field=models.CharField(default='✉️', max_length=50, verbose_name='آیکون ایمیل'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_address_icon',
            field=models.CharField(default='📍', max_length=50, verbose_name='آیکون آدرس'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_hours_icon',
            field=models.CharField(default='🕐', max_length=50, verbose_name='آیکون ساعات کاری'),
        ),
        # Add footer fields
        migrations.AddField(
            model_name='sitesettings',
            name='footer_background_color',
            field=models.CharField(default='#0f1c2e', max_length=20, verbose_name='رنگ پس‌زمینه فوتر'),
        ),
    ]