# Generated by Django 5.2.7 on 2025-11-03

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_split_large_migration_part4'),
    ]

    operations = [
        # Final part of the split migration - handle image fields
        # Add hero image field
        migrations.AddField(
            model_name='sitesettings',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/', verbose_name='تصویر هرو'),
        ),
        # Add service image fields
        migrations.AddField(
            model_name='sitesettings',
            name='service_loan_image',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='تصویر خدمات وام'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service_leasing_image',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='تصویر خدمات لیزینگ'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service_registration_image',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='تصویر خدمات ثبت شرکت'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service_legal_image',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='تصویر خدمات حقوقی'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service_licenses_image',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='تصویر خدمات ثبت مجوزها'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='service_commercial_image',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='تصویر خدمات کارت بازرگانی'),
        ),
        # Add loan image fields
        migrations.AddField(
            model_name='sitesettings',
            name='loan_mortgage_image',
            field=models.ImageField(blank=True, null=True, upload_to='loans/', verbose_name='تصویر وام مسکن'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='loan_car_image',
            field=models.ImageField(blank=True, null=True, upload_to='loans/', verbose_name='تصویر وام خودرو'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='loan_business_image',
            field=models.ImageField(blank=True, null=True, upload_to='loans/', verbose_name='تصویر وام کسب‌وکار'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='loan_investment_image',
            field=models.ImageField(blank=True, null=True, upload_to='loans/', verbose_name='تصویر وام سرمایه‌گذاری'),
        ),
        # Add leasing image field
        migrations.AddField(
            model_name='sitesettings',
            name='leasing_image',
            field=models.ImageField(blank=True, null=True, upload_to='leasing/', verbose_name='تصویر لیزینگ'),
        ),
        # Add registration image fields
        migrations.AddField(
            model_name='sitesettings',
            name='registration_company_image',
            field=models.ImageField(blank=True, null=True, upload_to='registration/', verbose_name='تصویر ثبت شرکت'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='registration_license_image',
            field=models.ImageField(blank=True, null=True, upload_to='registration/', verbose_name='تصویر اخذ مجوزها'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='registration_commercial_image',
            field=models.ImageField(blank=True, null=True, upload_to='registration/', verbose_name='تصویر کارت بازرگانی'),
        ),
        # Add testimonial image fields
        migrations.AddField(
            model_name='sitesettings',
            name='testimonial_1_image',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='تصویر نظر ۱'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='testimonial_2_image',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='تصویر نظر ۲'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='testimonial_3_image',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='تصویر نظر ۳'),
        ),
    ]