# Generated by Django 5.2.7 on 2025-11-03

from django.db import migrations, models, connection
import django.utils.timezone
import uuid

def check_and_add_fields(apps, schema_editor):
    """Check if fields exist before adding them to avoid duplicate column errors"""
    db_alias = schema_editor.connection.alias
    
    # Get list of existing columns
    cursor = connection.cursor()
    cursor.execute("""
        SELECT COLUMN_NAME 
        FROM INFORMATION_SCHEMA.COLUMNS 
        WHERE TABLE_SCHEMA = DATABASE() 
        AND TABLE_NAME = 'website_sitesettings'
    """)
    
    existing_columns = [row[0] for row in cursor.fetchall()]
    
    # Fields we want to ensure exist
    required_fields = {
        'site_uuid': "ALTER TABLE website_sitesettings ADD COLUMN site_uuid CHAR(32) UNIQUE",
        'created_at': "ALTER TABLE website_sitesettings ADD COLUMN created_at DATETIME",
        'updated_at': "ALTER TABLE website_sitesettings ADD COLUMN updated_at DATETIME",
        'social_instagram_url': "ALTER TABLE website_sitesettings ADD COLUMN social_instagram_url VARCHAR(200)",
        'social_telegram_url': "ALTER TABLE website_sitesettings ADD COLUMN social_telegram_url VARCHAR(200)",
        'social_linkedin_url': "ALTER TABLE website_sitesettings ADD COLUMN social_linkedin_url VARCHAR(200)",
        'social_twitter_url': "ALTER TABLE website_sitesettings ADD COLUMN social_twitter_url VARCHAR(200)",
        'hero_title': "ALTER TABLE website_sitesettings ADD COLUMN hero_title VARCHAR(200)",
        'hero_icon': "ALTER TABLE website_sitesettings ADD COLUMN hero_icon VARCHAR(50)",
        'services_background_color': "ALTER TABLE website_sitesettings ADD COLUMN services_background_color VARCHAR(20)",
        'site_keywords': "ALTER TABLE website_sitesettings ADD COLUMN site_keywords TEXT",
        'site_author': "ALTER TABLE website_sitesettings ADD COLUMN site_author VARCHAR(100)",
        'is_active': "ALTER TABLE website_sitesettings ADD COLUMN is_active TINYINT(1)",
        'site_version': "ALTER TABLE website_sitesettings ADD COLUMN site_version VARCHAR(20)",
    }
    
    # Add fields that don't exist
    for field_name, sql in required_fields.items():
        if field_name not in existing_columns:
            try:
                cursor.execute(sql)
                print(f"Added field {field_name}")
            except Exception as e:
                print(f"Could not add field {field_name}: {e}")
        else:
            print(f"Field {field_name} already exists")

def reverse_check_and_add_fields(apps, schema_editor):
    """Reverse operation - no need to remove fields in reverse migration"""
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_split_large_migration_images'),
    ]

    operations = [
        migrations.RunPython(check_and_add_fields, reverse_code=reverse_check_and_add_fields),
    ]